version: '3.8'

services:
  whisper-monolith:
    build:
      context: .
      dockerfile: Dockerfile.monolith
    container_name: whisper-transcription-new
    ports:
      - "8001:8000" # Mapeando para porta 8001 no host
    volumes:
      # Mapeie os diretórios do host para os diretórios do container
      - ./input:/app/input
      - ./input_web:/app/input_web
      - ./output_parts:/app/output_parts
      - ./output:/app/output
      - ./logs:/app/logs
      # Mapeie o diretório da WebUI React (build final)
      - ./webui/dist:/app/webui/dist
      - ./uploads:/app/uploads
      # Mapeie o .env para o container (se estiver usando variáveis de ambiente)
      # - ./.env:/app/.env
    environment:
      # Certifique-se de que estas variáveis estejam definidas no seu .env ou aqui
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: unless-stopped
    # Adicionando limites de recursos (opcional, mas bom para produção)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '3.5'
    #       memory: 20G
